# Generated by Django 6.0.2 on 2026-03-02 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="config",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
